sudo: false
language: python
python:
  - 3.3
  - 3.4
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - python setup.py develop
script: nosetests
branches:
  only:
    - master
    - feature/add_reference_test
